version: '3.8'

services:
  db:
    image: mysql:8
    container_name: summary_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: summary_paper
      MYSQL_USER: summary_user
      MYSQL_PASSWORD: summary_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "sleep 5 && alembic upgrade head && python seed.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    container_name: summary_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Tránh lỗi ghi đè thư mục node_modules từ máy thật vào docker
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: summary_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: summary_user
      PMA_PASSWORD: summary_pass
    depends_on:
      - db

  metabase:
    image: metabase/metabase:latest
    container_name: summary_metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
  metabase_data:
