"""Add metadata fields to users and papers

Revision ID: 42d0ab46bb58
Revises: bd8fbcf3372f
Create Date: 2026-05-09 20:42:35.534865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d0ab46bb58'
down_revision: Union[str, Sequence[str], None] = 'bd8fbcf3372f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='paper_status'), server_default='uploaded', nullable=False))
    op.add_column('papers', sa.Column('processing_time_seconds', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('papers', 'updated_at')
    op.drop_column('papers', 'error_message')
    op.drop_column('papers', 'processing_time_seconds')
    op.drop_column('papers', 'status')
    op.drop_column('papers', 'page_count')
    # ### end Alembic commands ###
